# Generated by Django 4.2.6 on 2023-11-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_id', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Online_Orders', models.BooleanField(default=False, null=True)),
                ('Booking_Table', models.BooleanField(default=False, null=True)),
                ('Ratings', models.FloatField(default=0)),
                ('Votes', models.IntegerField(default=0)),
                ('Restaurant_Type', models.CharField(max_length=200, null=True)),
                ('Cuisines', models.CharField(max_length=200, null=True)),
                ('Cost', models.IntegerField(default=0)),
                ('Type', models.CharField(max_length=200, null=True)),
                ('City', models.CharField(max_length=200, null=True)),
                ('Mean_Rating', models.FloatField(default=0)),
                ('User_Ratings', models.FloatField(default=0)),
            ],
        ),
    ]
