# Generated by Django 4.2.7 on 2023-11-20 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_delete_orderplaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
