# Generated by Django 4.2.7 on 2023-11-20 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_orderplaced_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
