# Generated by Django 4.2.7 on 2023-11-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_orderplaced_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderplaced',
            options={'verbose_name': 'Orderplaced', 'verbose_name_plural': 'Orderplaceds'},
        ),
    ]
