# Generated by Django 4.2.7 on 2023-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_orderplaced_city_orderplaced_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='Cost',
            field=models.IntegerField(default=0),
        ),
    ]
